spring:
# 服务名称
  application:
    name: test-springboot-mongo
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
#      uri: mongodb://localhost:27017/testdb?replSet=rs0
      host: localhost
      port: 27017
      database: testdb
# jackson设置
  jackson:
    #日期格式化
    date-format: "yyyy-MM-dd HH:mm:ss"
    #spring.jackson.date-format=yyyy-MM-dd
    #格式化输出
    serialization.indent_output: true
    #忽略无法转换的对象
    serialization.fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: non_null
    #允许对象忽略json中不存在的属性
    deserialization.fail_on_unknown_properties: false
    #允许出现特殊字符和转义符
    parser.allow_unquoted_control_chars: true
    #允许出现单引号
    parser.allow_single_quotes: true

server:
  port: 8888
  servlet:
    context-path: /test


